### ISSUE TITLE
Can I use this code with expo

### ISSUE THREAD

**Issue by obsd** [doo/scanbot-sdk-example-react-native#10]
I want to add expo to your sample app will it work?

**Comment by tailsu** [comment]
We haven't tested it, but it's likely that you can use expo to manage the project' build, granted that you can follow all of the SDK integration instructions for React Native in the context of expo. That said, you will most certainly not be able to use the SDK from the expo client app, because our SDK depends on native components which the expo client doesn't have built-in.

If you stumble upon concrete integration problems, you may open a new issue explaining your situation.
